"""Initial migration

Revision ID: 47d6c375dfa0
Revises: 0c0bacb8cf58
Create Date: 2025-04-27 11:59:38.892528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d6c375dfa0'
down_revision = '0c0bacb8cf58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipelines_is_default'), ['is_default'], unique=False)

    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pipeline_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'pipelines', ['pipeline_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pipeline_stages', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pipeline_id')

    with op.batch_alter_table('pipelines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pipelines_is_default'))

    op.drop_table('pipelines')
    # ### end Alembic commands ###
